config/routes.rb
Events::Application.routes.draw do
	root 'events#index'
  # get 'events' => 'events#index' 
  # get 'events/new' => 'events#new'
  # get 'events/:id' => 'events#show', as: "event"
  # get 'events/:id/edit' => 'events#edit', as: 'edit_event'
  # patch 'events/:id' => 'events#update'
  resources :events
end

app/models/event.rb
class Event < ActiveRecord::Base
	def free?
		price.blank? || price.zero?
	end

	def self.upcoming
		where('starts_at >= ?', Time.now).order('starts_at')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.upcoming
	end

	def show
		@event = Event.find(params[:id])
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		@event.update(event_params)
		redirect_to @event
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		@event.save
		redirect_to @event
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
	end

	private
		def event_params
			params.require(:event).
				permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/events_helper.rb
module EventsHelper
	def format_price(event)
		if event.free?  
			content_tag(:strong, "Free!")
		else
			number_to_currency(event.price)
		end
	end

	def image_for(event)
		if event.image_file_name.blank?
			image_tag 'placeholder.png', size: "150"
		else
			image_tag event.image_file_name, size: "150"
		end
	end
end

app/views/events/_form.html.erb
<div id='form'> 
	<%= form_for(@event) do |f| %>
		<p>
			<%= f.label :name%>
		</p>

		<p>
			<%= f.text_field :name, autofocus: true %>
		</p>

		<p>
			<%= f.label :description %>
		</p>
		<p>
			<%= f.text_area :description, cols:40, rows:7%>
		</p>

		<p>
			<%= f.label :location %>
		</p>
		<p>
			<%= f.text_field :location%>
		</p>

		<p>
			<%= f.label :price %>
		</p>
		<p>
			<%= f.number_field :price, cols:40, rows:7%>
		</p>

		<p>
			<%= f.label :starts_at %>
		</p>
		<p>
			<%= f.datetime_select :starts_at%>
		</p>

		<p>
			<%= f.label :image_file_name %>
		</p>
		<p>
			<%= f.text_field :image_file_name, size: 30, 
			placeholder: "GIF, JPG, or PNG file name" %>
		</p>

		<p>
			<%= f.label :capacity %>
		</p>
		<p>
			<%= f.number_field :capacity%>
		</p>

		<p id = 'options2'>
			<%= f.submit %>
			<button> <%= link_to 'Cancel', events_path %> </button>
		</p>
	<% end %>	
</div>

app/views/events/edit.html.erb
<h1>Editing <%= @event.name %> </h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1 class= 'center-header'> <%= pluralize(@events.size, 'Event')%> </h1>

<% @events.each do |event| %>
	<article class='event'>
		<header>
			<%= image_for(event) %>
			<h2><%= link_to(event.name, event)  %></h2>
			<h3><%= pluralize(event.capacity, 'spot') %></h3>
		</header>
			<p>
				<%= truncate(event.description, length: 30, separator: ' ') %>
			</p>
			<table>
				<tr>
					<th>When:</th>
					<td><%= event.starts_at %></td>
				</tr>
				<tr>
					<th>Where:</th>
					<td><%= event.location %></td>
				</tr>
				<tr>
					<th>Price:</th>
					<td><%= format_price(event) %> </td>
				</tr>
			</table>
	</article>
	<% end %>

app/views/events/new.html.erb
<div class = 'center-header'>
	<h1 class='events'>Add new event</h1>
</div>

<%= render 'form' %>

app/views/events/show.html.erb
	<article class='event'>
		<header>
			<%= image_for(@event) %>

			<h2><%= @event.name %></h2>
		</header>
			<p>
				<%= @event.description %>
			</p>
			<table>
				<tr>
					<th>When:</th>
					<td><%= @event.starts_at %></td>
				</tr>
				<tr>
					<th>Where:</th>
					<td><%= @event.location %></td>
				</tr>
				<tr>
					<th>Price:</th>
					<td><%= format_price(@event) %> </td>
				</tr>
				<tr>
					<th>Capacity:</th>
					<td><%= pluralize(@event.capacity, 'spot') %></td>
				</tr>
			</table>
			<div id ="options">
				<%= link_to "Edit", edit_event_path(@event) %> |

				<%= link_to 'Delete', event_path(@event), method: :delete, data: {confirm: 'Are you sure?'} %>
			</div>
	</article>

app/views/layouts/_footer.html.erb
<footer id = "page-footer">
			Copyright &copy; 2014 <%= link_to 'Zack Fisch', 'http://www.zfisch.com' %>
		</p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
		<h1>Event Planner</h1>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
		<nav>
			<ul>
				<li>
					<%= link_to 'All Events', events_path %>
				</li>
				<li>
					<%= link_to 'Add New Event', new_event_path %>
				</li>
			</ul>
		</nav>
	</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Events</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<%= render 'layouts/sidebar' %>

	<%= yield %>
	
	<%= render 'layouts/footer' %>

</body>
</html>